<div class="doctors" style="margin-bottom: 30px">
    <div class="col-md-2">
        <div class="circle-color color-1">
            <h5> Климентьев В.Г. (каб. 404)</h5>
        </div>
    </div>
    <div class="col-md-2">
        <div class="circle-color color-2">
            <h5> Барский М.Л. (каб. 404)</h5>
        </div>
    </div>
    <div class="col-md-2">
        <div class="circle-color color-3">
            <h5> Шиленко Д.Р. (каб. 404)</h5>
        </div>
    </div>
    <div class="col-md-2">
        <div class="circle-color color-4">
            <h5> Сабадош О.Р. (каб. 404)</h5>
        </div>
    </div>
    <div class="col-md-2">
        <div class="circle-color color-5">
            <h5> Ющенко Л.Ф. (каб. 404)</h5>
        </div>
    </div>
</div>

<div class="dhx_cal_container panel" id="scheduler_here">
    <div class="template:event_text">
        <a style='color:white;' href='http://google.com/search?q={event.id}'>{event.text}</a>
    </div>
    <div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:100%;'>
        <div class="dhx_cal_navline">
            <div class="dhx_cal_prev_button">&nbsp;</div>
            <div class="dhx_cal_next_button">&nbsp;</div>
            <div class="dhx_cal_today_button"></div>
            <div class="dhx_cal_date"></div>
            <div class="dhx_minical_icon" id="dhx_minical_icon" onclick="AgereCommunicator.show_minical()">&nbsp;</div>
            <div class="dhx_cal_tab" name="week_tab"></div>
            <div class="dhx_cal_tab" name="month_tab"></div>
            <div class="dhx_cal_tab" name   ="unit_tab"></div>
        </div>
        <div class="dhx_cal_header">
        </div>
        <div class="dhx_cal_data">
        </div>
    </div>

</div>

<script>
    console.log(event);
</script>
